import { createPactEngine } from './engine.js';
import { LocalStorageSnapshotStore } from './persistence.js';
import { createPactOrchestrator } from './orchestrator.js';

const $ = id => document.getElementById(id);
const store = new LocalStorageSnapshotStore();
let revision = 0;
let engine;
let flow;
function toast(message){ $('toast').textContent=message; $('toast').hidden=false; $('live').textContent=message; clearTimeout(toast.timer); toast.timer=setTimeout(()=>$('toast').hidden=true,2600); }
async function persist(){ try{ const next=await store.write(revision,engine.exportSnapshot()); revision=next.revision; }catch(error){ setTimeout(()=>location.reload(),100); throw error; } }
function setPhases(active){ document.querySelectorAll('[data-phase]').forEach(el=>{ const order=['PLAN','SAFETY','APPROVAL','COMMIT','VERIFY','RECEIPT']; const i=order.indexOf(el.dataset.phase), a=order.indexOf(active); el.classList.toggle('done',i<a); el.classList.toggle('active',i===a); }); }
function render(){ const s=engine.inspect(), tx=s.transaction; if(!tx){$('demo-state').textContent='READY';return;} $('demo-state').textContent=tx.state; if(tx.effects){$('demo-summary').innerHTML=`<div><small>PLAN</small><strong>${tx.effects.length} effects</strong></div><div><small>RISK</small><strong>Guardrails pass</strong></div><div><small>AUTHORITY</small><strong>${tx.state==='PREVIEWED'?'Awaiting you':tx.state}</strong></div>`;$('demo-diff').innerHTML=tx.effects.map(e=>`<div class="diff"><code>${e.path}</code><span>${String(e.before)} → <b>${String(e.after)}</b></span></div>`).join('');} if(tx.state==='PREVIEWED'){setPhases('APPROVAL');$('demo-run').hidden=true;$('demo-approve').hidden=false;$('demo-explanation').innerHTML='<b>PACT needs exactly one decision.</b><p>The plan is complete, invariants passed and the hash is fixed. Approval grants a short-lived capability for this plan only.</p>';} if(tx.state==='VERIFIED'){setPhases('RECEIPT');document.querySelector('[data-phase="RECEIPT"]').classList.add('done');$('demo-approve').hidden=true;$('demo-receipt').hidden=false;$('demo-receipt-hash').textContent=tx.receipt.receiptHash;$('demo-explanation').innerHTML='<b>Finished automatically.</b><p>PACT committed the exact approved effects, verified canonical state and anchored this receipt without another human step.</p>';}}
async function boot(){let saved;try{saved=await store.read()}catch(error){throw new Error(`PERSISTENCE_INTEGRITY_FAILED:${error.message}`)}revision=saved.revision;engine=createPactEngine({snapshot:saved.value??undefined});try{await engine.validateIntegrity()}catch(error){throw new Error(`PERSISTENCE_INTEGRITY_FAILED:${error.message}`)}flow=createPactOrchestrator({engine,persist});const state=engine.inspect().transaction?.state;if(state === 'COMMITTED'){setPhases('VERIFY');$('demo-state').textContent='RECOVERING';$('demo-explanation').innerHTML='<b>PACT recovered a durable commit.</b><p>The transaction had already committed before interruption. PACT is resuming verification only—without another approval and without re-running the commit.</p>';await flow.resumeCommitted();}else if(state === 'APPROVED'){setPhases('COMMIT');$('demo-state').textContent='RECOVERING';$('demo-explanation').innerHTML='<b>PACT recovered approved authority.</b><p>The exact plan was already approved. PACT is continuing commit and verification automatically.</p>';await flow.resumeApproved();}render();}
$('demo-run').addEventListener('click',async()=>{try{setPhases('PLAN');$('demo-state').textContent='AUTOPILOT';$('demo-explanation').innerHTML='<b>Planning automatically.</b><p>PACT is deriving semantic effects and validating safety constraints. No authority exists yet.</p>';await flow.begin();render()}catch(e){toast(e.message)}});
$('demo-approve').addEventListener('click',async event=>{try{setPhases('COMMIT');$('demo-state').textContent='FINISHING';$('demo-explanation').innerHTML='<b>Authority granted.</b><p>PACT is committing, verifying postconditions and generating the receipt automatically.</p>';await flow.approveAndFinish({trusted:event.isTrusted});render()}catch(e){toast(e.message);render()}});
boot().catch(e=>toast(`BOOT_FAILED: ${e.message}`));
